server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true     #访问路径可以显示IP地址

zuul:
  routes:
    # old address
    mydept.serviceId: microservicecloud-dept
    # new address
    mydept.path: /test/**
    myfeign.serviceId: microservicecloud-feign
    myfeign.path: /feigntest/**
    # mydept.host: 8251
    # hide true address
  # ignored-services: "*"
  # prefix name
  # prefix: /liangzisong
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
management:
  security:
    enabled: false